name: FitCat
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "16.0"

targets:
  FitCat:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - FitCat
    info:
      path: FitCat/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourname.fitcat
      SWIFT_VERSION: "5.9"
      INFOPLIST_FILE: FitCat/Info.plist
    dependencies:
      - package: SQLite

  FitCatTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FitCatTests
    dependencies:
      - target: FitCat

packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift
    from: 0.15.0
